package causality

import "time"

// EventID is a strongly typed identifier
type EventID string

// CausalEvent is a Generic Event Node compatible with Go 1.24 (generics).
// T allows us to store either Raw Text (for processing) or Vector Embeddings (for search).
type CausalEvent[T any] struct {
	ID             EventID
	Timestamp      time.Time
	Summary        string
	NeutralSummary string    // Generated by "Emotional Noise Filter"
	TrustScore     float64   // Calculated via "Bridging Consensus"
	Payload        T         // Generics: Could be string or float32 (vector)
	Causes         []EventID // Upstream parents (DAG)
	Effects        []EventID // Downstream children
}

// CausalEdge represents the graph connection in Dgraph
type CausalEdge struct {
	From       EventID
	To         EventID
	Type       string  // "TRIGGERED", "ESCALATED"
	Confidence float64 // 0.0 - 1.0 (from Gemini)
}

// AnalysisResult matches the JSON output from the "Causal Oracle" prompt.
type AnalysisResult struct {
	EventProcessing struct {
		OriginalHeadline string     `json:"original_headline"`
		NeutralHeadline  string     `json:"neutral_headline"`
		EmotionalScore   float64    `json:"emotional_score"`
		BridgingScore    float64    `json:"bridging_score"`
		KeyFacts         []string   `json:"key_facts"`
		CausalLinks      []LinkInfo `json:"causal_links"`
	} `json:"event_processing"`
	UIDirectives struct {
		NodeColorHex       string `json:"node_color_hex"`
		SwimlaneAssignment string `json:"swimlane_assignment"`
	} `json:"ui_directives"`
}

type LinkInfo struct {
	TargetEventID string  `json:"target_event_id"`
	Reason        string  `json:"reason"`
	Confidence    float64 `json:"confidence"`
	Type          string  `json:"type"`
}
